-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."workflow_refids_mapping" add column "min_app_version_code" integer
--  not null default '0';
