-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."assessments" add column "student_id" character varying(15)
--  null;
