-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."workflow_refids_mapping" add column "subject_id" integer
--  null;
