-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update school_list AS s
-- set block_id = b.id
-- from blocks b
-- where b.name = s.block;
