-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."school_list" add column "geo_fence_enabled" boolean
--  not null default 'True';
