-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update school_list AS s
-- set district_id = d.id
-- from districts d
-- where d.name = s.district;
