-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."competency_mapping" add column "pass_percent" integer
--  not null default '75';
