-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."competency_mapping" add column "metadata" jsonb
--  not null default jsonb_build_object();
