-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update mentor AS m
-- set district_id = d.id
-- from districts d
-- where d.name = m.district_name;
