-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."assessment_cycle_district_school_mapping" add column "class_2_students" jsonb
--  not null;
