-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."assessments" add column "is_valid" boolean
--  not null default 'true';
